В прилагаемом файле представлены данные, собранные путем голосования за самые лучшие (или, по крайней мере, самые популярные) конфеты Хэллоуина. Обучите модель линейной многомерной регрессии. В качестве предикторов выступают поля: chocolate, fruity, caramel, peanutyalmondy, nougat, crispedricewafer, hard, bar, pluribus, sugarpercent, pricepercent, отклик — winpercent.

В качестве тренировочного набора данных используйте данные из файла, за иключением следующих конфет: Air Heads, Kit Kat. Обучите модель. Если используете Azure ML Studio, укажите random seed = 2019 в параметрах блока Linear Regression.

In [2]:
import numpy as np 
import pandas as pd 
from sklearn.linear_model import LinearRegression

In [44]:
data = pd.read_csv('candy-data.csv', delimiter=',', index_col='competitorname')
train_data = data.drop(['Air Heads', 'Kit Kat'])

In [45]:
X = pd.DataFrame(train_data.drop(['winpercent', 'Y'], axis=1))

Y = pd.DataFrame(train_data['winpercent'])


chocolate  fruity  caramel  peanutyalmondy  nougat  \
competitorname                                                           
100 Grand                   1       0        1               0       0   
3 Musketeers                1       0        0               0       1   
One dime                    0       0        0               0       0   
One quarter                 0       0        0               0       0   
Almond Joy                  1       0        0               1       0   
Baby Ruth                   1       0        1               1       1   
Boston Baked Beans          0       0        0               1       0   
Candy Corn                  0       0        0               0       0   
Caramel Apple Pops          0       1        1               0       0   
Charleston Chew             1       0        0               0       1   

                    crispedricewafer  hard  bar  pluribus  sugarpercent  \
competitorname                                                            
100 Grand                          1     0    1         0         0.732   
3 Musketeers                       0     0    1         0         0.604   
One dime                           0     0    0         0         0.011   
One quarter                        0     0    0         0         0.011   
Almond Joy                         0     0    1         0         0.465   
Baby Ruth                          0     0    1         0         0.604   
Boston Baked Beans                 0     0    0         1         0.313   
Candy Corn                         0     0    0         1         0.906   
Caramel Apple Pops                 0     0    0         0         0.604   
Charleston Chew                    0     0    1         0         0.604   

                    pricepercent  
competitorname                    
100 Grand                  0.860  
3 Musketeers               0.511  
One dime                   0.116  
One quarter                0.511  
Almond Joy                 0.767  
Baby Ruth                  0.767  
Boston Baked Beans         0.511  
Candy Corn                 0.325  
Caramel Apple Pops         0.325  
Charleston Chew            0.511

In [46]:
reg = LinearRegression().fit(X, Y)


In [47]:
AirHeads = data.loc['Air Heads',:].to_frame().T
reg.predict(AirHeads.drop(['winpercent', 'Y'], axis=1))


array([[52.89627581]])

In [48]:
KitKat = data.loc['Kit Kat',:].to_frame().T
reg.predict(KitKat.drop(['winpercent', 'Y'], axis=1))

array([[62.36513914]])

In [50]:
reg.predict([[1, 1, 1, 0, 1, 0, 1, 1, 1, 0.669, 0.456]])

array([[61.26894586]])